language: go
os:
  - linux
  - osx
go:
  - 1.8
  - 1.9
  - master
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
script:
  - go test -v -tags ci ./...
  - $GOPATH/bin/goveralls -service=travis-ci
